[package]
name = "midi-driver"
version = "0.1.0"
edition = "2024"

[dependencies]
midir = "0.10.3"
once_cell = "1.21.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"

[lib]
crate-type = ["cdylib"]
