name = "8x8 MIDI Grid"
id = "note-midi-grid"

[[cells]]
type = "grid-mixer"
w = 8
h = 8

[[cells.controls]]
type = "notebutton"
channel = 1
note = 1
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 2
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 3
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 4
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 5
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 6
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 7
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 8
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 9
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 10
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 11
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 12
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 13
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 14
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 15
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 16
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 17
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 18
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 19
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 20
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 21
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 22
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 23
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 24
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 25
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 26
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 27
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 28
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 29
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 30
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 31
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 32
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 33
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 34
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 35
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 36
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 37
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 38
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 39
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 40
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 41
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 42
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 43
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 44
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 45
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 46
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 47
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 48
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 49
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 50
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 51
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 52
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 53
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 54
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 55
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 56
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 57
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 58
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 59
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 60
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 61
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 62
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 63
mode = "trigger"

[[cells.controls]]
type = "notebutton"
channel = 1
note = 64
mode = "trigger"