name = "Fullscreen XY Pad with Note"
id = "fullscreen-xy-pad"
program = 1

[[cells]]
type = "horiz-mixer"

[[cells.horiz]]
type = "xypad"
channel = 2
label = "XY Pad"
note = 32

[cells.horiz.x]
cc = 4

[cells.horiz.y]
cc = 5


[[cells.horiz]]
type = "ccslider"
id = "vol_slider"
channel = 1
cc = 6
mode = "relative"
label = "Volume"
vertical = false