name = "Fullscreen XY Pad"
id = "fullscreen-xy-pad"

[[cells]]
type = "vert-mixer"

[[cells.controls]]
type = "xypad"
channel = 2
label = "XY Pad"
#note = 60

[cells.controls.x]
cc = 4

[cells.controls.y]
cc = 5