name = "Phone Dual Volume"
id = "phone-dual-volume"

[[cells]]
type = "horiz-mixer"

[[cells.horiz]]
type = "ccslider"
channel = 1
cc = 0
default_value = 127
mode = "snapback"
label = "Volume 1"

[[cells.horiz]]
type = "ccslider"
channel = 1
cc = 1
default_value = 127
mode = "snapback"
label = "Volume 1"