name = "Phone Dual Volume"
id = "phone-dual-volume"

[[cells]]
type = "horiz-mixer"

[[cells.controls]]
type = "ccslider"
channel = 2
cc = 1
default_value = 127
mode = "snapback"
label = "Volume 1"

[[cells.controls]]
type = "ccslider"
channel = 2
cc = 2
default_value = 127
mode = "snapback"
label = "Volume 1"