name = "Shift Test"
id = "shift_test"

[[cells]]
type = "shift"
note = 1
channel = 3

[[cells.a.controls]]
type = "vert-mixer"

[[cells.a.controls.controls]]
type = "ccslider"
channel = 1
cc = 1
mode = "relative"
label = "Test 1"

[[cells.a.controls.controls]]
type = "notebutton"
channel = 3
note = 1
label = "Shift"
mode = "trigger"

#[[cells.b]]

[[cells.b.controls]]
type = "xypad"
channel = 1
label = "XY Pad"

[cells.b.controls.x]
cc = 4

[cells.b.controls.y]
cc = 5