name = "Nested Test TOML"
id = "nested_toml"

[[cells]]
type = "horiz-mixer"

[[cells.horiz]]
type = "horiz-mixer"

[[cells.horiz.horiz]]
type = "vert-mixer"

[[cells.horiz.horiz.vert]]
type = "ccslider"
channel = 1
cc = 1
mode = "relative"
label = "Test 1"

[[cells.horiz.horiz.vert]]
type = "ccslider"
channel = 1
cc = 2
mode = "relative"
label = "Test 1"

[[cells.horiz.horiz.vert]]
type = "xypad"
channel = 1
label = "XY Pad"

[cells.horiz.horiz.vert.x]
cc = 4

[cells.horiz.horiz.vert.y]
cc = 5