name = "One-device Traktor 2.0"
id = "traktor_performance"

[[cells]]
type = "vert-mixer"

# DECK A
[[cells.vert]]
type = "grid-mixer"
id = "deck_a"
w = 4
h = 2

[[cells.vert.grid]]
type = "notebutton"
channel = 1
note = 16
label = "1/4 Loop"
mode = "trigger"

[[cells.vert.grid]]
type = "notebutton"
channel = 1
note = 15
label = "1/2 Loop"
mode = "trigger"

[[cells.vert.grid]]
type = "notebutton"
channel = 1
note = 14
label = "1 Loop"
mode = "trigger"

[[cells.vert.grid]]
type = "notebutton"
channel = 1
note = 13
label = "2 Loop"
mode = "trigger"

[[cells.vert.grid]]
type = "notebutton"
channel = 1
note = 12
label = "4 Loop"
mode = "trigger"

[[cells.vert.grid]]
type = "notebutton"
channel = 1
note = 11
label = "8 Loop"
mode = "trigger"

[[cells.vert.grid]]
type = "notebutton"
channel = 1
note = 10
label = "16 Loop"
mode = "trigger"

[[cells.vert.grid]]
type = "notebutton"
channel = 1
note = 9
label = "32 Loop"
mode = "trigger"

[[cells.vert]]
type = "horiz-mixer"

[[cells.vert.horiz]]
type = "rotary"
channel = 1
default_value = 64
cc = 17
label = "Bass"
mode = "snapback"

[[cells.vert.horiz]]
type = "rotary"
channel = 1
cc = 16
default_value = 64
label = "Mid"
mode = "snapback"

[[cells.vert.horiz]]
type = "rotary"
channel = 1
cc = 15
default_value = 64
label = "Hi"
mode = "snapback"

[[cells.vert]]
type = "horiz-mixer"

[[cells.vert.horiz]]
type = "notebutton"
channel = 1
note = 1
label = "Play/Pause"
mode = "trigger"

[[cells.vert.horiz]]
type = "notebutton"
channel = 1
note = 2
label = "Sync"
mode = "trigger"

# VOLUME SLIDER
[[cells]]
type = "horiz-mixer"
id = "levels"

[[cells.horiz]]
type = "ccslider"
channel = 1
cc = 0
mode = "relative"
label = "Test"

[[cells.horiz]]
type = "ccslider"
channel = 1
cc = 1
mode = "relative"
label = "Test"

# DECK B
[[cells]]
type = "grid-mixer"
id = "deck_b"
w = 4
h = 8

[[cells.grid]]
type = "notebutton"
channel = 1
note = 36
label = "1/4 Loop"
mode = "trigger"

[[cells.grid]]
type = "notebutton"
channel = 1
note = 35
label = "1/2 Loop"
mode = "trigger"

[[cells.grid]]
type = "notebutton"
channel = 1
note = 34
label = "1 Loop"
mode = "trigger"

[[cells.grid]]
type = "notebutton"
channel = 1
note = 33
label = "2 Loop"
mode = "trigger"

[[cells.grid]]
type = "notebutton"
channel = 1
note = 32
label = "4 Loop"
mode = "trigger"

[[cells.grid]]
type = "notebutton"
channel = 1
note = 31
label = "8 Loop"
mode = "trigger"

[[cells.grid]]
type = "notebutton"
channel = 1
note = 30
label = "16 Loop"
mode = "trigger"

[[cells.grid]]
type = "notebutton"
channel = 1
note = 29
label = "32 Loop"
mode = "trigger"

[[cells.grid]]
type = "notebutton"
channel = 1
note = 47
label = "Kill Bass"
mode = "trigger"

[[cells.grid]]
type = "notebutton"
channel = 1
note = 48
label = "Kill Mid"
mode = "trigger"

[[cells.grid]]
type = "notebutton"
channel = 1
note = 49
label = "Kill Hi"
mode = "trigger"

[[cells.grid]]
type = "empty"

[[cells.grid]]
type = "notebutton"
channel = 1
note = 21
label = "Play/Pause"
mode = "trigger"

[[cells.grid]]
type = "notebutton"
channel = 1
note = 22
label = "Sync"
mode = "trigger"