name: "Build Bindings"
description: "Build Bindings"

inputs:
    target:
        required: true

runs:
    using: "composite"
    steps:
        - name: Export Bindings
          shell: bash
          run: cargo test --all