name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache-dependency-path: web/yarn.lock

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.4.0

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y libjack-dev libasound-dev

      - name: Export Bindings
        #working-directory: ./web
        run: cargo test --all

      - name: Build Web UI
        working-directory: ./web
        run: yarn && yarn build:release
        
      - name: Build MIDI Driver (Mac)
        if: matrix.os == 'macos-latest'
        working-directory: ./midi-driver
        #run: cargo build -p midi-driver --release
        run: deno task compile:mac:release

      - name: Build MIDI Driver (Windows)
        if: matrix.os == 'windows-latest'
        working-directory: ./midi-driver
        #run: cargo build -p midi-driver --release
        run: deno task compile:win:release

      - name: Build MIDI Driver (Linux)
        if: matrix.os == 'ubuntu-latest'
        working-directory: ./midi-driver
        #run: cargo build -p midi-driver --release
        run: deno task compile:linux:release

      - name: Build Server (Linux)
        if: matrix.os == 'ubuntu-latest'
        working-directory: ./server
        run: deno task compile:linux:release

      - name: Build Server (Mac)
        if: matrix.os == 'macos-latest'
        working-directory: ./server
        run: deno task compile:mac:release

      - name: Build Server (Win)
        if: matrix.os == 'windows-latest'
        working-directory: ./server
        run: deno task compile:win:release

      - name: Rename Output (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: mv server/homebrewdj midi-controller-linux
        
      - name: Rename Output (MacOS)
        if: matrix.os == 'macos-latest'
        run: mv server/homebrewdj midi-controller-macos
        
      - name: Rename Output (Windows)
        if: matrix.os == 'windows-latest'
        run: mv server/homebrewdj.exe midi-controller-win.exe
        
      - name: Package WebUI and Vendor Files
        if: matrix.os == 'ubuntu-latest'
        run: |
          zip -r webui.zip web/dist
          zip -r overlays.zip overlays

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: midi-controller-${{ runner.os }}
          path: |
            midi-controller-linux
            midi-controller-macos
            midi-controller-win.exe
            target/release/list_ports
            target/release/list_ports.exe
            midi-driver/native/libmidi_driver.dylib
            midi-driver/native/libmidi_driver.so
            midi-driver/native/midi_driver.dll
            midi-driver/native/libmidi_driver.h
            midi-driver/native/libmidi_driver.pc
            overlays.zip
            webui.zip
            LICENSE

      - name: Release (on tags only)
        uses: softprops/action-gh-release@master
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: |
            midi-controller-linux
            midi-controller-macos
            midi-controller-win.exe
            midi-driver/native/libmidi_driver.dylib
            midi-driver/native/libmidi_driver.so
            midi-driver/native/midi_driver.dll
            midi-driver/native/libmidi_driver.h
            midi-driver/native/libmidi_driver.pc
            overlays.zip
            webui.zip
            LICENSE
