name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          #cache: yarn
          cache-dependency-path: web/yarn.lock


      #- run: cargo test --all-features


      #- uses: denoland/setup-deno@v1
      #  with:
      #    deno-version: v2.x

      - name: Build Web UI
        working-directory: ./web
        run: yarn && yarn build

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y libjack-dev libasound-dev

      - name: Build executable
        run: cargo build --release

      - name: Rename Output (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: mv target/release/midi-controller midi-controller-linux

      - name: Rename Output (MacOS)
        if: matrix.os == 'macos-latest'
        run: mv target/release/midi-controller midi-controller-macos

      - name: Rename Output (Windows)
        if: matrix.os == 'windows-latest'
        run: mv target/release/midi-controller.exe midi-controller-win.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: midi-controller-${{ runner.os }}
          path: |
            midi-controller-linux
            midi-controller-macos
            midi-controller-win.exe

      - name: Release (on tags only)
        uses: softprops/action-gh-release@master
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          files: |
            midi-controller-linux
            midi-controller-macos
            midi-controller-win.exe
