[package]
name = "web"
version = "0.1.11"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["fs", "rt", "macros"] }
toml = "0.9.11"
ts-rs = "11.1.0"
